# Generated by Django 6.0.4 on 2026-08-19 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_choice_options_remove_quiz_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='quiz.quiz'),
        ),
    ]
